swagger: "2.0"
info:
  description: "GAPSI REST Excercise"
  version: "1.0.0"
  title: "GAPSI REST Excercise"
basePath: "/v1"
tags:
- name: "item"
  description: "Information about Items"
schemes:
- "https"
- "http"
paths:
  /item/{itemId}:
    get:
      tags:
      - "item"
      summary: "Finds item by Id"
      description: ""
      operationId: "getItemById"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "itemId"
        in: "path"
        description: "ID of item to return"
        required: true
        type: "string"
        maxLength: 10
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/Item"
        400:
          description: "Invalid ID supplied"
        404:
          description: "Item not found"
    post:
      tags:
      - "item"
      summary: "Updates an item with form data"
      description: ""
      operationId: "updateItemWithForm"
      consumes:
      - "application/x-www-form-urlencoded"
      produces:
      - "application/json"
      parameters:
      - name: "itemId"
        in: "path"
        description: "ID of item that needs to be updated"
        required: true
        type: "string"
        maxLength: 10
      - name: "description"
        in: "formData"
        description: "Updated description of the item"
        required: false
        type: "string"
        maxLength: 200
      - name: "model"
        in: "formData"
        description: "Updated model of the item"
        required: false
        type: "string"
        maxLength: 10
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/ApiResponse"
        405:
          description: "Invalid input"
  definitions:
    Item:
      type: "object"
      properties:
        id:
          type: "string"
          maxLength: 10
          readOnly: true
        name:
          type: "string"
          maxLength: 20
          readOnly: true
        description:
          type: "string"
          maxLength: 200
        price:
          type: "number"
          format: "float"
          readOnly: true
        model:
          type: "string"
          maxLength: 10
    ApiResponse:
      type: "object"
      properties:
        returnCode:
          type: "integer"
          format: "int32"
        message:
          type: "string"
    